apiVersion: v1
kind: Service
metadata:
  name: my-rig-ui-svc
  labels:
    app: rig-ui
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: rig-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-rig-ui
  labels:
    app: rig-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rig-ui
  template:
    metadata:
      labels:
        app: rig-ui
    spec:
      containers:
      - name: rig-ui
        image: arunmohanraj/whatviz:latest
        ports:
        - containerPort: 80